### ISSUE TITLE
Antifragility

### ISSUE THREAD

**Issue by dfjhh** [G2BCN/Glosario-AgileITSM#13]
Robustez

**Comment by avallesalas** [comment]
Si bien a primera vista parece una traducción correcta, el  propio inventor del término indica que es diferente que robustez...

https://en.wikipedia.org/wiki/Antifragility

`In his book, Taleb stresses the differences between antifragile and robust/resilient. "Antifragility is beyond resilience or robustness. The resilient resists shocks and stays the same; the antifragile gets better."`

**Comment by dfjhh** [comment]
La traducción del título del libro es español es tal cual "Antifrágil" como aparece en https://es.wikipedia.org/wiki/Nassim_Taleb#Obras y https://www.casadellibro.com/libro-antifragil-las-cosas-que-se-benefician-del-desorden/9788408149637/2665137 por lo que creo sería según indicas.

**Comment by avallesalas** [comment]
Asi, pues, la cierro... Gracias por tu colaboración!!
